# -*- coding: utf-8 -*-
"""global_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNVHVjpaEmicllZz2Ua5059oeUxdD-U7
"""

!unzip /content/drive/MyDrive/sentinal_data/ISLES-2022.zip -d /content/

import numpy as np
import nibabel as nib
import pandas as pd
import json
from pathlib import Path
from scipy.ndimage import zoom
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

class ISLESGlobalPreprocessor:
    def __init__(self, raw_data_path, output_path, target_spacing=(1.95, 1.95, 1.95)):
        self.raw_data_path = Path(raw_data_path)
        self.output_path = Path(output_path)
        self.target_spacing = np.array(target_spacing)

        self.nnunet_path = self.output_path / 'nnunet_format'
        self.monai_path = self.output_path / 'monai_format'
        self.metadata_path = self.output_path / 'metadata'

        self.case_records = []
        self.failed_cases = []

        self._setup_directories()

    def _setup_directories(self):
        for split in ['Tr', 'Ts']:
            (self.nnunet_path / f'images{split}').mkdir(parents=True, exist_ok=True)
            (self.nnunet_path / f'labels{split}').mkdir(parents=True, exist_ok=True)

        for split in ['train', 'val', 'test']:
            (self.monai_path / split / 'images').mkdir(parents=True, exist_ok=True)
            (self.monai_path / split / 'labels').mkdir(parents=True, exist_ok=True)

        self.metadata_path.mkdir(parents=True, exist_ok=True)

    def discover_cases(self):
        return sorted([
            p.name for p in self.raw_data_path.iterdir()
            if p.is_dir() and p.name.startswith('sub-strokecase')
        ])

    def get_file_paths(self, subject_id):
        session = 'ses-0001'
        base = self.raw_data_path / subject_id / session

        return {
            'dwi': base / 'dwi' / f'{subject_id}_{session}_dwi.nii.gz',
            'adc': base / 'dwi' / f'{subject_id}_{session}_adc.nii.gz',
            'flair': base / 'anat' / f'{subject_id}_{session}_FLAIR.nii.gz',
            'mask': self.raw_data_path / 'derivatives' / subject_id / session /
                    f'{subject_id}_{session}_msk.nii.gz'
        }

    def compute_target_shape(self, shape, src_spacing):
        scale = src_spacing / self.target_spacing
        return tuple(np.round(np.array(shape) * scale).astype(int))

    def resample_volume(self, vol, src_spacing, tgt_shape, order):
        zoom_factors = src_spacing / self.target_spacing
        zoom_factors *= np.array(tgt_shape) / np.array(vol.shape)

        out = zoom(vol, zoom_factors, order=order, mode='constant', cval=0)

        if out.shape != tgt_shape:
            tmp = np.zeros(tgt_shape, dtype=out.dtype)
            slices = tuple(slice(0, min(out.shape[i], tgt_shape[i])) for i in range(3))
            tmp[slices] = out[slices]
            out = tmp

        return out

    def conservative_crop(self, volumes, mask=None, padding=10):
        union = np.zeros_like(volumes[0], dtype=bool)
        for v in volumes:
            union |= (v > 0)

        coords = np.where(union)
        if len(coords[0]) == 0:
            return volumes, mask, {}

        z0 = int(max(coords[0].min() - padding, 0))
        z1 = int(min(coords[0].max() + padding + 1, volumes[0].shape[0]))
        y0 = int(max(coords[1].min() - padding, 0))
        y1 = int(min(coords[1].max() + padding + 1, volumes[0].shape[1]))
        x0 = int(max(coords[2].min() - padding, 0))
        x1 = int(min(coords[2].max() + padding + 1, volumes[0].shape[2]))

        cropped_vols = [v[z0:z1, y0:y1, x0:x1] for v in volumes]
        cropped_mask = mask[z0:z1, y0:y1, x0:x1] if mask is not None else None

        crop_bbox = {
            'z': [z0, z1],
            'y': [y0, y1],
            'x': [x0, x1]
        }

        return cropped_vols, cropped_mask, crop_bbox

    def compute_intensity_stats(self, vol, mask):
        vox = vol[mask] if mask is not None and mask.sum() > 0 else vol[vol > 0]

        if len(vox) == 0:
            return {
                'p1': 0.0, 'p99': 0.0,
                'mean': 0.0, 'std': 1.0,
                'min': 0.0, 'max': 0.0
            }

        return {
            'p1': float(np.percentile(vox, 1)),
            'p99': float(np.percentile(vox, 99)),
            'mean': float(np.mean(vox)),
            'std': float(np.std(vox)),
            'min': float(np.min(vox)),
            'max': float(np.max(vox))
        }

    def clip_intensity(self, vol, stats):
        return np.clip(vol, stats['p1'], stats['p99'])

    def analyze_lesion(self, mask):
        voxel_count = int(mask.sum())
        volume_ml = (voxel_count * np.prod(self.target_spacing)) / 1000.0

        if voxel_count == 0:
            category = 'none'
        elif volume_ml < 5:
            category = 'small'
        elif volume_ml < 50:
            category = 'medium'
        else:
            category = 'large'

        return volume_ml, category, voxel_count

    def process_case(self, subject_id, idx, split='train'):
        paths = self.get_file_paths(subject_id)

        for key, path in paths.items():
            if not path.exists():
                raise FileNotFoundError(f"Missing {key}: {path}")

        dwi_nii = nib.load(paths['dwi'])
        adc_nii = nib.load(paths['adc'])
        flair_nii = nib.load(paths['flair'])
        mask_nii = nib.load(paths['mask'])

        dwi_data = dwi_nii.get_fdata().astype(np.float32)
        adc_data = adc_nii.get_fdata().astype(np.float32)
        flair_data = flair_nii.get_fdata().astype(np.float32)
        mask_data = (mask_nii.get_fdata() > 0).astype(np.uint8)

        original_spacing = np.abs(np.diag(dwi_nii.affine)[:3])

        tgt_shape = self.compute_target_shape(dwi_data.shape, original_spacing)

        dwi_r = self.resample_volume(dwi_data, original_spacing, tgt_shape, order=3)
        adc_r = self.resample_volume(adc_data, original_spacing, tgt_shape, order=3)
        flair_r = self.resample_volume(flair_data, original_spacing, tgt_shape, order=3)
        mask_r = self.resample_volume(mask_data, original_spacing, tgt_shape, order=0)

        [dwi_r, adc_r, flair_r], mask_r, crop_bbox = self.conservative_crop(
            [dwi_r, adc_r, flair_r], mask_r, padding=10
        )

        brain_mask = (dwi_r > 0) | (adc_r > 0) | (flair_r > 0)

        stats_dwi = self.compute_intensity_stats(dwi_r, brain_mask)
        stats_adc = self.compute_intensity_stats(adc_r, brain_mask)
        stats_flair = self.compute_intensity_stats(flair_r, brain_mask)

        dwi_r = self.clip_intensity(dwi_r, stats_dwi)
        adc_r = self.clip_intensity(adc_r, stats_adc)
        flair_r = self.clip_intensity(flair_r, stats_flair)

        lesion_ml, category, voxel_count = self.analyze_lesion(mask_r)

        affine = np.eye(4)
        affine[:3, :3] = np.diag(self.target_spacing)

        case_id = f'case_{idx:04d}'

        self._save_nnunet_format(case_id, dwi_r, adc_r, flair_r, mask_r, affine, split)
        self._save_monai_format(case_id, dwi_r, adc_r, flair_r, mask_r, affine, split)

        metadata = {
            'case_id': case_id,
            'subject_id': subject_id,
            'split': split,
            'original_shape': [int(x) for x in dwi_data.shape],
            'resampled_shape': [int(x) for x in tgt_shape],
            'final_shape': [int(x) for x in dwi_r.shape],
            'original_spacing': [float(x) for x in original_spacing],
            'target_spacing': [float(x) for x in self.target_spacing],
            'crop_bbox': crop_bbox,
            'lesion_volume_ml': float(lesion_ml),
            'lesion_voxels': int(voxel_count),
            'lesion_category': category,
            'intensity_stats': {
                'dwi': stats_dwi,
                'adc': stats_adc,
                'flair': stats_flair
            }
        }

        with open(self.metadata_path / f'{case_id}_metadata.json', 'w') as f:
            json.dump(metadata, f, indent=2)

        return metadata

    def _save_nnunet_format(self, case_id, dwi, adc, flair, mask, affine, split):
        suffix = 'Tr' if split == 'train' else 'Ts'

        img_dir = self.nnunet_path / f'images{suffix}'
        lbl_dir = self.nnunet_path / f'labels{suffix}'

        nib.save(nib.Nifti1Image(dwi, affine), img_dir / f'{case_id}_0000.nii.gz')
        nib.save(nib.Nifti1Image(adc, affine), img_dir / f'{case_id}_0001.nii.gz')
        nib.save(nib.Nifti1Image(flair, affine), img_dir / f'{case_id}_0002.nii.gz')
        nib.save(nib.Nifti1Image(mask, affine), lbl_dir / f'{case_id}.nii.gz')

    def _save_monai_format(self, case_id, dwi, adc, flair, mask, affine, split):
        img_dir = self.monai_path / split / 'images'
        lbl_dir = self.monai_path / split / 'labels'

        stacked = np.stack([dwi, adc, flair], axis=0)

        nib.save(nib.Nifti1Image(stacked, affine), img_dir / f'{case_id}.nii.gz')
        nib.save(nib.Nifti1Image(mask, affine), lbl_dir / f'{case_id}.nii.gz')

    def create_dataset_json(self):
        dataset_info = {
            "channel_names": {
                "0": "DWI",
                "1": "ADC",
                "2": "FLAIR"
            },
            "labels": {
                "background": 0,
                "lesion": 1
            },
            "numTraining": len([r for r in self.case_records if r['split'] == 'train']),
            "numTest": len([r for r in self.case_records if r['split'] == 'test']),
            "file_ending": ".nii.gz",
            "dataset_name": "ISLES2022",
            "reference": "https://isles22.grand-challenge.org/",
            "description": "Ischemic stroke lesion segmentation from DWI, ADC, and FLAIR"
        }

        with open(self.nnunet_path / 'dataset.json', 'w') as f:
            json.dump(dataset_info, f, indent=2)

    def create_monai_datalist(self):
        datalist = {
            'training': [],
            'validation': [],
            'testing': []
        }

        for record in self.case_records:
            case_id = record['case_id']
            split_map = {'train': 'training', 'val': 'validation', 'test': 'testing'}
            split_key = split_map[record['split']]

            entry = {
                'image': f"{record['split']}/images/{case_id}.nii.gz",
                'label': f"{record['split']}/labels/{case_id}.nii.gz",
                'case_id': case_id
            }
            datalist[split_key].append(entry)

        with open(self.monai_path / 'datalist.json', 'w') as f:
            json.dump(datalist, f, indent=2)

    def run(self, train_ratio=0.7, val_ratio=0.15):
        print("=" * 60)
        print("ISLES Global Preprocessing Pipeline")
        print("=" * 60)

        cases = self.discover_cases()
        print(f"\nFound {len(cases)} cases")

        n_train = int(len(cases) * train_ratio)
        n_val = int(len(cases) * val_ratio)

        train_cases = cases[:n_train]
        val_cases = cases[n_train:n_train + n_val]
        test_cases = cases[n_train + n_val:]

        print(f"Split: {len(train_cases)} train, {len(val_cases)} val, {len(test_cases)} test")

        print("\nProcessing cases...")
        idx = 1

        for split, case_list in [('train', train_cases), ('val', val_cases), ('test', test_cases)]:
            for subject_id in tqdm(case_list, desc=f"Processing {split}"):
                try:
                    metadata = self.process_case(subject_id, idx, split)
                    self.case_records.append(metadata)
                    idx += 1
                except Exception as e:
                    print(f"\nFailed: {subject_id} - {str(e)}")
                    self.failed_cases.append({
                        'subject_id': subject_id,
                        'split': split,
                        'error': str(e)
                    })

        print("\nCreating summary files...")

        df_records = pd.DataFrame(self.case_records)
        df_records.to_csv(self.metadata_path / 'case_records.csv', index=False)

        if self.failed_cases:
            df_failed = pd.DataFrame(self.failed_cases)
            df_failed.to_csv(self.metadata_path / 'failed_cases.csv', index=False)

        self.create_dataset_json()
        self.create_monai_datalist()

        print("\n" + "=" * 60)
        print("PREPROCESSING COMPLETE")
        print("=" * 60)
        print(f"Successfully processed: {len(self.case_records)} cases")
        print(f"Failed cases: {len(self.failed_cases)}")

        if len(self.case_records) > 0:
            print("\nLesion size distribution:")
            print(df_records['lesion_category'].value_counts())
            print(f"\nAverage lesion volume: {df_records['lesion_volume_ml'].mean():.2f} mL")

        print(f"\nOutput saved to: {self.output_path}")
        print(f"   nnunet_format/  (for nnU-Net v2)")
        print(f"   monai_format/   (for Swin-UNETR & SegResNet)")
        print(f"   metadata/       (statistics & metadata)")

if __name__ == "__main__":
    RAW_DATA_PATH = "/content/ISLES-2022"
    OUTPUT_PATH = "/content/preprocessed_data"

    preprocessor = ISLESGlobalPreprocessor(
        raw_data_path=RAW_DATA_PATH,
        output_path=OUTPUT_PATH,
        target_spacing=(1.95, 1.95, 1.95)
    )

    preprocessor.run(
        train_ratio=0.7,
        val_ratio=0.15
    )

    print("\nReady for training:")
    print("   nnU-Net v2: Use nnunet_format/")
    print("   Swin-UNETR: Use monai_format/")
    print("   SegResNet: Use monai_format/")

!cp -r /content/preprocessed_data  /content/drive/MyDrive/

import numpy as np
import nibabel as nib
import json
import pandas as pd
from pathlib import Path
from scipy.ndimage import zoom
from tqdm import tqdm


class ISLESGlobalPreprocessor:
    def __init__(self, raw_data_path, output_path, target_spacing=(1.95, 1.95, 1.95)):
        self.raw_data_path = Path(raw_data_path)
        self.output_path = Path(output_path)
        self.target_spacing = np.array(target_spacing)

        self.nnunet_path = self.output_path / 'nnunet_format'
        self.monai_path = self.output_path / 'monai_format'
        self.metadata_path = self.output_path / 'metadata'

        self.case_records = []
        self.failed_cases = []

        self._setup_directories()

    def _setup_directories(self):
        """Create directory structure for both nnU-Net and MONAI formats"""
        # nnU-Net format
        for split in ['Tr', 'Ts']:
            (self.nnunet_path / f'images{split}').mkdir(parents=True, exist_ok=True)
            (self.nnunet_path / f'labels{split}').mkdir(parents=True, exist_ok=True)

        # MONAI format
        for split in ['train', 'val', 'test']:
            (self.monai_path / split / 'images').mkdir(parents=True, exist_ok=True)
            (self.monai_path / split / 'labels').mkdir(parents=True, exist_ok=True)

        # Metadata
        self.metadata_path.mkdir(parents=True, exist_ok=True)

    def discover_cases(self):
        """Find all subject directories in the raw data"""
        cases = sorted([
            p.name for p in self.raw_data_path.iterdir()
            if p.is_dir() and p.name.startswith('sub-strokecase')
        ])
        print(f"Discovered {len(cases)} cases in raw data")
        return cases

    def get_file_paths(self, subject_id):
        """Get file paths for all modalities and mask for a subject"""
        session = 'ses-0001'
        base = self.raw_data_path / subject_id / session

        return {
            'dwi': base / 'dwi' / f'{subject_id}_{session}_dwi.nii.gz',
            'adc': base / 'dwi' / f'{subject_id}_{session}_adc.nii.gz',
            'flair': base / 'anat' / f'{subject_id}_{session}_FLAIR.nii.gz',
            'mask': self.raw_data_path / 'derivatives' / subject_id / session /
                    f'{subject_id}_{session}_msk.nii.gz'
        }

    def compute_target_shape(self, shape, src_spacing):
        """Calculate target shape after resampling to target spacing"""
        scale = src_spacing / self.target_spacing
        return tuple(np.round(np.array(shape) * scale).astype(int))

    def resample_volume(self, vol, src_spacing, tgt_shape, order):
        """Resample volume to target spacing and shape"""
        zoom_factors = src_spacing / self.target_spacing
        zoom_factors *= np.array(tgt_shape) / np.array(vol.shape)

        out = zoom(vol, zoom_factors, order=order, mode='constant', cval=0)

        # Ensure exact target shape
        if out.shape != tgt_shape:
            tmp = np.zeros(tgt_shape, dtype=out.dtype)
            slices = tuple(slice(0, min(out.shape[i], tgt_shape[i])) for i in range(3))
            tmp[slices] = out[slices]
            out = tmp

        return out

    def conservative_crop(self, volumes, mask=None, padding=10):
        """Crop volumes to region containing data with padding"""
        # Find union of all non-zero regions
        union = np.zeros_like(volumes[0], dtype=bool)
        for v in volumes:
            union |= (v > 0)

        coords = np.where(union)
        if len(coords[0]) == 0:
            return volumes, mask, {}

        # Calculate bounding box with padding
        z0 = int(max(coords[0].min() - padding, 0))
        z1 = int(min(coords[0].max() + padding + 1, volumes[0].shape[0]))
        y0 = int(max(coords[1].min() - padding, 0))
        y1 = int(min(coords[1].max() + padding + 1, volumes[0].shape[1]))
        x0 = int(max(coords[2].min() - padding, 0))
        x1 = int(min(coords[2].max() + padding + 1, volumes[0].shape[2]))

        # Crop all volumes
        cropped_vols = [v[z0:z1, y0:y1, x0:x1] for v in volumes]
        cropped_mask = mask[z0:z1, y0:y1, x0:x1] if mask is not None else None

        crop_bbox = {
            'z': [z0, z1],
            'y': [y0, y1],
            'x': [x0, x1]
        }

        return cropped_vols, cropped_mask, crop_bbox

    def compute_intensity_stats(self, vol, mask):
        """Compute intensity statistics for normalization"""
        vox = vol[mask] if mask is not None and mask.sum() > 0 else vol[vol > 0]

        if len(vox) == 0:
            return {
                'p1': 0.0, 'p99': 0.0,
                'mean': 0.0, 'std': 1.0,
                'min': 0.0, 'max': 0.0
            }

        return {
            'p1': float(np.percentile(vox, 1)),
            'p99': float(np.percentile(vox, 99)),
            'mean': float(np.mean(vox)),
            'std': float(np.std(vox)),
            'min': float(np.min(vox)),
            'max': float(np.max(vox))
        }

    def clip_intensity(self, vol, stats):
        """Clip intensity values to percentile range"""
        return np.clip(vol, stats['p1'], stats['p99'])

    def analyze_lesion(self, mask):
        """Analyze lesion size and categorize"""
        voxel_count = int(mask.sum())
        volume_ml = (voxel_count * np.prod(self.target_spacing)) / 1000.0

        if voxel_count == 0:
            category = 'none'
        elif volume_ml < 5:
            category = 'small'
        elif volume_ml < 50:
            category = 'medium'
        else:
            category = 'large'

        return volume_ml, category, voxel_count

    def process_case(self, subject_id, idx, split='train'):
        """Process a single case through the full pipeline"""
        paths = self.get_file_paths(subject_id)

        # Verify all files exist
        for key, path in paths.items():
            if not path.exists():
                raise FileNotFoundError(f"Missing {key}: {path}")

        # Load all modalities
        dwi_nii = nib.load(paths['dwi'])
        adc_nii = nib.load(paths['adc'])
        flair_nii = nib.load(paths['flair'])
        mask_nii = nib.load(paths['mask'])

        dwi_data = dwi_nii.get_fdata().astype(np.float32)
        adc_data = adc_nii.get_fdata().astype(np.float32)
        flair_data = flair_nii.get_fdata().astype(np.float32)
        mask_data = (mask_nii.get_fdata() > 0).astype(np.uint8)

        # Get original spacing
        original_spacing = np.abs(np.diag(dwi_nii.affine)[:3])

        # Compute target shape
        tgt_shape = self.compute_target_shape(dwi_data.shape, original_spacing)

        # Resample all volumes
        dwi_r = self.resample_volume(dwi_data, original_spacing, tgt_shape, order=3)
        adc_r = self.resample_volume(adc_data, original_spacing, tgt_shape, order=3)
        flair_r = self.resample_volume(flair_data, original_spacing, tgt_shape, order=3)
        mask_r = self.resample_volume(mask_data, original_spacing, tgt_shape, order=0)

        # Crop to region of interest
        [dwi_r, adc_r, flair_r], mask_r, crop_bbox = self.conservative_crop(
            [dwi_r, adc_r, flair_r], mask_r, padding=10
        )

        # Compute brain mask
        brain_mask = (dwi_r > 0) | (adc_r > 0) | (flair_r > 0)

        # Compute intensity statistics
        stats_dwi = self.compute_intensity_stats(dwi_r, brain_mask)
        stats_adc = self.compute_intensity_stats(adc_r, brain_mask)
        stats_flair = self.compute_intensity_stats(flair_r, brain_mask)

        # Clip intensities
        dwi_r = self.clip_intensity(dwi_r, stats_dwi)
        adc_r = self.clip_intensity(adc_r, stats_adc)
        flair_r = self.clip_intensity(flair_r, stats_flair)

        # Analyze lesion
        lesion_ml, category, voxel_count = self.analyze_lesion(mask_r)

        # Create affine with target spacing
        affine = np.eye(4)
        affine[:3, :3] = np.diag(self.target_spacing)

        # Generate case ID
        case_id = f'case_{idx:04d}'

        # Save in both formats
        self._save_nnunet_format(case_id, dwi_r, adc_r, flair_r, mask_r, affine, split)
        self._save_monai_format(case_id, dwi_r, adc_r, flair_r, mask_r, affine, split)

        # Create metadata
        metadata = {
            'case_id': case_id,
            'subject_id': subject_id,
            'split': split,
            'original_shape': [int(x) for x in dwi_data.shape],
            'resampled_shape': [int(x) for x in tgt_shape],
            'final_shape': [int(x) for x in dwi_r.shape],
            'original_spacing': [float(x) for x in original_spacing],
            'target_spacing': [float(x) for x in self.target_spacing],
            'crop_bbox': crop_bbox,
            'lesion_volume_ml': float(lesion_ml),
            'lesion_voxels': int(voxel_count),
            'lesion_category': category,
            'intensity_stats': {
                'dwi': stats_dwi,
                'adc': stats_adc,
                'flair': stats_flair
            }
        }

        # Save individual case metadata
        with open(self.metadata_path / f'{case_id}_metadata.json', 'w') as f:
            json.dump(metadata, f, indent=2)

        return metadata

    def _save_nnunet_format(self, case_id, dwi, adc, flair, mask, affine, split):
        """
        Save in nnU-Net format
        FIXED: Val cases now go to training folder
        """
        # CRITICAL FIX: Train and Val both go to imagesTr
        if split in ['train', 'val']:
            suffix = 'Tr'
        else:  # test
            suffix = 'Ts'

        img_dir = self.nnunet_path / f'images{suffix}'
        lbl_dir = self.nnunet_path / f'labels{suffix}'

        # Save with .nii.gz extension
        nib.save(nib.Nifti1Image(dwi, affine), img_dir / f'{case_id}_0000.nii.gz')
        nib.save(nib.Nifti1Image(adc, affine), img_dir / f'{case_id}_0001.nii.gz')
        nib.save(nib.Nifti1Image(flair, affine), img_dir / f'{case_id}_0002.nii.gz')
        nib.save(nib.Nifti1Image(mask, affine), lbl_dir / f'{case_id}.nii.gz')

    def _save_monai_format(self, case_id, dwi, adc, flair, mask, affine, split):
        """Save in MONAI format (multi-channel stacked)"""
        img_dir = self.monai_path / split / 'images'
        lbl_dir = self.monai_path / split / 'labels'

        # Stack modalities as channels
        stacked = np.stack([dwi, adc, flair], axis=0)

        nib.save(nib.Nifti1Image(stacked, affine), img_dir / f'{case_id}.nii.gz')
        nib.save(nib.Nifti1Image(mask, affine), lbl_dir / f'{case_id}.nii.gz')

    def create_dataset_json(self):
        """
        Create nnU-Net dataset.json
        FIXED: Counts train+val together
        """
        dataset_info = {
            "channel_names": {
                "0": "DWI",
                "1": "ADC",
                "2": "FLAIR"
            },
            "labels": {
                "background": 0,
                "lesion": 1
            },
            # CRITICAL FIX: Count train + val together for nnU-Net
            "numTraining": len([r for r in self.case_records if r['split'] in ['train', 'val']]),
            "numTest": len([r for r in self.case_records if r['split'] == 'test']),
            "file_ending": ".nii.gz",
            "dataset_name": "ISLES2022",
            "reference": "https://isles22.grand-challenge.org/",
            "description": "Ischemic stroke lesion segmentation from DWI, ADC, and FLAIR"
        }

        with open(self.nnunet_path / 'dataset.json', 'w') as f:
            json.dump(dataset_info, f, indent=2)

    def create_monai_datalist(self):
        """Create MONAI datalist.json"""
        datalist = {
            'training': [],
            'validation': [],
            'testing': []
        }

        for record in self.case_records:
            case_id = record['case_id']
            split_map = {'train': 'training', 'val': 'validation', 'test': 'testing'}
            split_key = split_map[record['split']]

            entry = {
                'image': f"{record['split']}/images/{case_id}.nii.gz",
                'label': f"{record['split']}/labels/{case_id}.nii.gz",
                'case_id': case_id
            }
            datalist[split_key].append(entry)

        with open(self.monai_path / 'datalist.json', 'w') as f:
            json.dump(datalist, f, indent=2)

    def verify_output(self):
        """Verify the output structure and completeness"""
        print("\n" + "="*70)
        print("VERIFYING OUTPUT")
        print("="*70)

        # Check nnU-Net format
        imagesTr_files = list((self.nnunet_path / 'imagesTr').glob('*_0000.nii.gz'))
        labelsTr_files = list((self.nnunet_path / 'labelsTr').glob('*.nii.gz'))
        imagesTs_files = list((self.nnunet_path / 'imagesTs').glob('*_0000.nii.gz'))
        labelsTs_files = list((self.nnunet_path / 'labelsTs').glob('*.nii.gz'))

        print(f"\nnnU-Net format:")
        print(f"  imagesTr: {len(imagesTr_files)} cases ({len(imagesTr_files)*3} total files expected)")
        print(f"  labelsTr: {len(labelsTr_files)} cases")
        print(f"  imagesTs: {len(imagesTs_files)} cases ({len(imagesTs_files)*3} total files expected)")
        print(f"  labelsTs: {len(labelsTs_files)} cases")

        # Verify modality completeness for first 5 training cases
        print(f"\n  Checking modality completeness (first 5 cases):")
        for case_file in imagesTr_files[:5]:
            case_id = case_file.stem.replace('_0000', '')
            dwi = (self.nnunet_path / 'imagesTr' / f'{case_id}_0000.nii.gz').exists()
            adc = (self.nnunet_path / 'imagesTr' / f'{case_id}_0001.nii.gz').exists()
            flair = (self.nnunet_path / 'imagesTr' / f'{case_id}_0002.nii.gz').exists()
            label = (self.nnunet_path / 'labelsTr' / f'{case_id}.nii.gz').exists()

            status = "✓" if all([dwi, adc, flair, label]) else "✗"
            print(f"    {status} {case_id}: DWI={dwi}, ADC={adc}, FLAIR={flair}, Label={label}")

        # Check dataset.json
        with open(self.nnunet_path / 'dataset.json', 'r') as f:
            ds_json = json.load(f)

        print(f"\n  dataset.json:")
        print(f"    numTraining: {ds_json['numTraining']} (expected: {len(imagesTr_files)})")
        print(f"    numTest: {ds_json['numTest']} (expected: {len(imagesTs_files)})")
        print(f"    file_ending: {ds_json['file_ending']}")

        # Verify match
        if ds_json['numTraining'] == len(imagesTr_files):
            print(f"    ✓ Training count matches")
        else:
            print(f"    ✗ Training count MISMATCH!")

        if ds_json['numTest'] == len(imagesTs_files):
            print(f"    ✓ Test count matches")
        else:
            print(f"    ✗ Test count MISMATCH!")

    def run(self, train_ratio=0.7, val_ratio=0.15):
        """Run the complete preprocessing pipeline"""
        print("="*70)
        print("ISLES 2022 - GLOBAL PREPROCESSING PIPELINE")
        print("="*70)

        # Discover cases
        cases = self.discover_cases()
        if len(cases) == 0:
            raise ValueError("No cases found! Check raw_data_path")

        print(f"\nTotal cases found: {len(cases)}")

        # Calculate split sizes
        n_train = int(len(cases) * train_ratio)
        n_val = int(len(cases) * val_ratio)

        train_cases = cases[:n_train]
        val_cases = cases[n_train:n_train + n_val]
        test_cases = cases[n_train + n_val:]

        print(f"\nData split:")
        print(f"  Train: {len(train_cases)} cases ({train_ratio*100:.0f}%)")
        print(f"  Val:   {len(val_cases)} cases ({val_ratio*100:.0f}%)")
        print(f"  Test:  {len(test_cases)} cases ({(1-train_ratio-val_ratio)*100:.0f}%)")

        # Process all cases
        print(f"\nProcessing cases...")
        idx = 1

        for split, case_list in [('train', train_cases), ('val', val_cases), ('test', test_cases)]:
            print(f"\nProcessing {split} split ({len(case_list)} cases)...")

            for subject_id in tqdm(case_list, desc=f"  {split}"):
                try:
                    metadata = self.process_case(subject_id, idx, split)
                    self.case_records.append(metadata)
                    idx += 1
                except Exception as e:
                    print(f"\n  ✗ Failed: {subject_id} - {str(e)}")
                    self.failed_cases.append({
                        'subject_id': subject_id,
                        'split': split,
                        'error': str(e)
                    })

        # Create summary files
        print(f"\nCreating summary files...")

        # Save case records
        df_records = pd.DataFrame(self.case_records)
        df_records.to_csv(self.metadata_path / 'case_records.csv', index=False)
        print(f"  ✓ case_records.csv saved ({len(df_records)} cases)")

        # Save failed cases if any
        if self.failed_cases:
            df_failed = pd.DataFrame(self.failed_cases)
            df_failed.to_csv(self.metadata_path / 'failed_cases.csv', index=False)
            print(f"  ⚠ failed_cases.csv saved ({len(df_failed)} failures)")

        # Create dataset.json and datalist.json
        self.create_dataset_json()
        print(f"  ✓ dataset.json created")

        self.create_monai_datalist()
        print(f"  ✓ datalist.json created")

        # Print statistics
        print("\n" + "="*70)
        print("PREPROCESSING COMPLETE")
        print("="*70)
        print(f"\nSuccessfully processed: {len(self.case_records)} / {len(cases)} cases")
        print(f"Failed cases: {len(self.failed_cases)}")

        if len(self.case_records) > 0:
            print(f"\nLesion size distribution:")
            print(df_records['lesion_category'].value_counts().to_string())
            print(f"\nLesion volume statistics:")
            print(f"  Mean: {df_records['lesion_volume_ml'].mean():.2f} mL")
            print(f"  Median: {df_records['lesion_volume_ml'].median():.2f} mL")
            print(f"  Min: {df_records['lesion_volume_ml'].min():.2f} mL")
            print(f"  Max: {df_records['lesion_volume_ml'].max():.2f} mL")

        print(f"\nOutput directory: {self.output_path}")
        print(f"  ├── nnunet_format/  (for nnU-Net v2)")
        print(f"  ├── monai_format/   (for Swin-UNETR & SegResNet)")
        print(f"  └── metadata/       (statistics & case info)")

        # Run verification
        self.verify_output()

        return len(self.case_records), len(self.failed_cases)


# ============================================================
# USAGE EXAMPLE
# ============================================================

if __name__ == "__main__":
    # Set your paths
    RAW_DATA_PATH = "/content/ISLES-2022"  # ← CHANGE THIS
    OUTPUT_PATH = "/content/preprocessed_output"  # ← CHANGE THIS

    # Initialize preprocessor
    preprocessor = ISLESGlobalPreprocessor(
        raw_data_path=RAW_DATA_PATH,
        output_path=OUTPUT_PATH,
        target_spacing=(1.95, 1.95, 1.95)
    )

    # Run preprocessing
    success_count, failed_count = preprocessor.run(
        train_ratio=0.7,
        val_ratio=0.15
    )

    print(f"\n✓ Preprocessing complete!")
    print(f"  Success: {success_count}")
    print(f"  Failed: {failed_count}")

!cp -r /content/preprocessed_output  /content/drive/MyDrive/

import nibabel as nib
img = nib.load("/content/preprocessed_output/nnunet_format/imagesTr/case_0001_0000.nii.gz")
print(img.shape)

from pathlib import Path

def verify_nnunet_dataset(nnunet_path, num_modalities=3):
    nnunet_path = Path(nnunet_path)

    imagesTr = nnunet_path / "imagesTr"
    labelsTr = nnunet_path / "labelsTr"
    imagesTs = nnunet_path / "imagesTs"
    labelsTs = nnunet_path / "labelsTs"

    print("\n" + "="*70)
    print("NNUNET DATASET VERIFICATION (FULL MODALITY CHECK)")
    print("="*70)

    def check_split(images_dir, labels_dir, split_name):
        image_files = sorted(images_dir.glob("*_0000.nii.gz"))

        print(f"\n[{split_name}]")
        print(f"Total cases detected: {len(image_files)}")

        missing_cases = []

        for img0 in image_files:
            case_id = img0.name.split("_0000")[0]

            # Check all modalities
            modality_ok = True
            for m in range(num_modalities):
                mod_file = images_dir / f"{case_id}_{m:04d}.nii.gz"
                if not mod_file.exists():
                    modality_ok = False
                    print(f"  ❌ Missing modality {m:04d} for {case_id}")

            # Check label
            label_file = labels_dir / f"{case_id}.nii.gz"
            if not label_file.exists():
                modality_ok = False
                print(f"  ❌ Missing label for {case_id}")

            if not modality_ok:
                missing_cases.append(case_id)

        if not missing_cases:
            print(f"  ✅ All {split_name} cases are complete")
        else:
            print(f"\n  ⚠ Incomplete cases in {split_name}: {len(missing_cases)}")
            for c in missing_cases:
                print(f"    - {c}")

        return len(missing_cases)

    # Run checks
    missing_tr = check_split(imagesTr, labelsTr, "TRAIN")
    missing_ts = check_split(imagesTs, labelsTs, "TEST")

    print("\n" + "="*70)
    if missing_tr == 0 and missing_ts == 0:
        print("✅ DATASET VERIFICATION PASSED — READY FOR nnU-Net v2")
    else:
        print("❌ DATASET VERIFICATION FAILED — FIX MISSING FILES")

    print("="*70)

verify_nnunet_dataset(
    nnunet_path="/content/preprocessed_output/nnunet_format",
    num_modalities=3
)

