# -*- coding: utf-8 -*-
"""nnU-Net_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4fUfvituATfVI_gz_XB0MHJYUyeN2NB
"""

!pip install -q nnunetv2
print("✓ nnU-Net v2 installed")

import os
from pathlib import Path
from google.colab import drive


BASE_DIR = Path("/content/drive/MyDrive/preprocessed_output/nnunet_format")

# Create nnU-Net directories
os.environ['nnUNet_raw'] = str(BASE_DIR / "nnUNet_raw")
os.environ['nnUNet_preprocessed'] = str(BASE_DIR / "nnUNet_preprocessed")
os.environ['nnUNet_results'] = str(BASE_DIR / "nnUNet_results")

for path in [os.environ['nnUNet_raw'], os.environ['nnUNet_preprocessed'], os.environ['nnUNet_results']]:
    Path(path).mkdir(parents=True, exist_ok=True)

print("="*70)
print("nnU-Net Environment Setup (Colab)")
print("="*70)
print(f"✓ nnUNet_raw: {os.environ['nnUNet_raw']}")
print(f"✓ nnUNet_preprocessed: {os.environ['nnUNet_preprocessed']}")
print(f"✓ nnUNet_results: {os.environ['nnUNet_results']}")

import os
import shutil
from pathlib import Path

# ===============================
# CONFIG
# ===============================
dataset_id = "001"
dataset_name = "ISLES2022"
dataset_full_name = f"Dataset{dataset_id}_{dataset_name}"

# nnU-Net raw directory (must be set in environment)
nnUNet_raw = Path(os.environ["nnUNet_raw"])
raw_dataset_path = nnUNet_raw / dataset_full_name

# Your existing dataset path in Drive
source_path = Path("/content/drive/MyDrive/preprocessed_output/nnunet_format")

print("="*70)
print("nnU-Net Dataset Setup (From Google Drive)")
print("="*70)

# Create target dataset directory
raw_dataset_path.mkdir(parents=True, exist_ok=True)

# ===============================
# COPY REQUIRED FOLDERS
# ===============================
folders_to_copy = ["imagesTr", "labelsTr", "imagesTs", "labelsTs"]

for folder in folders_to_copy:
    src = source_path / folder
    dst = raw_dataset_path / folder

    if src.exists():
        shutil.copytree(src, dst, dirs_exist_ok=True)
        file_count = len(list(dst.glob("*.nii.gz")))
        print(f"  ✓ {folder}: {file_count} files copied")
    else:
        print(f"  ⚠ {folder} not found in source")

# ===============================
# COPY dataset.json
# ===============================
dataset_json_src = source_path / "dataset.json"
dataset_json_dst = raw_dataset_path / "dataset.json"

if dataset_json_src.exists():
    shutil.copy(dataset_json_src, dataset_json_dst)
    print("  ✓ dataset.json copied")
else:
    raise FileNotFoundError("dataset.json not found!")

print("\n✅ Dataset successfully prepared for nnU-Net v2")
print(f"📁 Location: {raw_dataset_path}")

print("\n" + "="*70)
print("Dataset Verification")
print("="*70)

imagesTr_path = raw_dataset_path / "imagesTr"
labelsTr_path = raw_dataset_path / "labelsTr"
imagesTs_path = raw_dataset_path / "imagesTs"

train_cases = set()
for f in imagesTr_path.glob("*_0000.nii.gz"):
    case_id = f.name.replace("_0000.nii.gz", "")
    train_cases.add(case_id)

test_cases = set()
for f in imagesTs_path.glob("*_0000.nii.gz"):
    case_id = f.name.replace("_0000.nii.gz", "")
    test_cases.add(case_id)

print(f"\nCase counts:")
print(f"  Training: {len(train_cases)} cases")
print(f"  Test: {len(test_cases)} cases")
print(f"  Total: {len(train_cases) + len(test_cases)} cases")

print(f"\nVerifying first 3 training cases:")
for case_id in sorted(train_cases)[:3]:
    dwi = (imagesTr_path / f"{case_id}_0000.nii.gz").exists()
    adc = (imagesTr_path / f"{case_id}_0001.nii.gz").exists()
    flair = (imagesTr_path / f"{case_id}_0002.nii.gz").exists()
    label = (labelsTr_path / f"{case_id}.nii.gz").exists()
    complete = all([dwi, adc, flair, label])
    status = "✓" if complete else "✗"
    print(f"  {status} {case_id}: DWI={dwi}, ADC={adc}, FLAIR={flair}, Label={label}")

with open(dataset_json_dst, 'r') as f:
    ds_json = json.load(f)

print(f"\ndataset.json:")
print(f"  numTraining: {ds_json['numTraining']} (found: {len(train_cases)})")
print(f"  numTest: {ds_json['numTest']} (found: {len(test_cases)})")
print(f"  file_ending: {ds_json['file_ending']}")

if ds_json['numTraining'] == len(train_cases):
    print(f"  ✓ Training count matches")
else:
    print(f"  ✗ Training count mismatch!")
    print(f"    Updating dataset.json...")
    ds_json['numTraining'] = len(train_cases)
    ds_json['numTest'] = len(test_cases)
    with open(dataset_json_dst, 'w') as f:
        json.dump(ds_json, f, indent=2)
    print(f"  ✓ dataset.json updated")

print(f"\n✓ Dataset ready for nnU-Net")

print("\n" + "="*70)
print("nnU-Net Planning & Preprocessing")
print("="*70)
print("\nThis will take 30-60 minutes...")
print("Steps:")
print("  1. Verify dataset integrity")
print("  2. Analyze dataset properties")
print("  3. Determine optimal configuration")
print("  4. Preprocess all data")
print()

!nnUNetv2_plan_and_preprocess -d {dataset_id} --verify_dataset_integrity

print("\n✓ Planning and preprocessing complete!")

import json
from pathlib import Path
import os

plans_file = Path(os.environ['nnUNet_preprocessed']) / dataset_full_name / "nnUNetPlans.json"

print("="*70)
print("nnU-Net Configuration")
print("="*70)

if plans_file.exists():
    with open(plans_file, 'r') as f:
        plans = json.load(f)

    print(f"\nAvailable configurations: {list(plans['configurations'].keys())}")

    if '3d_fullres' in plans['configurations']:
        config = plans['configurations']['3d_fullres']
        arch = config["architecture"]

        print(f"\n3D Full Resolution Settings:")
        print(f"  Patch size: {config['patch_size']}")
        print(f"  Batch size: {config['batch_size']}")
        print(f"  Network class: {arch['network_class_name']}")
        print(f"  Conv type: {arch['arch_kwargs']['conv_op']}")
        print(f"  Feature maps per stage: {arch['arch_kwargs']['features_per_stage']}")
        print(f"  Number of stages: {arch['arch_kwargs']['n_stages']}")

        if config['batch_size'] == 1:
            print(f"\n  ⚠ Batch size is 1 (memory constrained)")
        else:
            print(f"\n  ✓ Batch size is {config['batch_size']}")

    print(f"\n✓ Plans look good!")
else:
    print(f"✗ Plans file not found at {plans_file}")

import subprocess
import time

def train_fold_with_resume(dataset_id, fold, max_attempts=10):
    command = [
        "nnUNetv2_train",
        str(dataset_id),
        "3d_fullres",
        str(fold),
        "--npz"
    ]
    results_path = Path(os.environ['nnUNet_results']) / dataset_full_name / "nnUNetTrainer__nnUNetPlans__3d_fullres"
    checkpoint_final = results_path / f"fold_{fold}" / "checkpoint_final.pth"

    for attempt in range(max_attempts):
        print("\n" + "="*70)
        print(f"Training Fold {fold} - Attempt {attempt + 1}/{max_attempts}")
        print("="*70)

        if checkpoint_final.exists():
            print(f"✓ Fold {fold} already complete!")
            return True

        fold_path = results_path / f"fold_{fold}"
        if fold_path.exists():
            checkpoints = list(fold_path.glob("checkpoint_*.pth"))
            if checkpoints:
                latest = max(checkpoints, key=lambda p: p.stat().st_mtime)
                print(f"  Found checkpoint: {latest.name}")
                print(f"  Resuming training...")

        try:
            print(f"\nStarting training...")
            print(f"Command: {' '.join(command)}\n")
            result = subprocess.run(command, check=True)
            if checkpoint_final.exists():
                print(f"\n✓ Fold {fold} training complete!")
                return True
        except subprocess.CalledProcessError as e:
            print(f"\n⚠ Training interrupted: {e}")
            print(f"   This is normal on Colab (session timeout)")
            print(f"   Will resume from checkpoint on next attempt...")
            time.sleep(10)
        except KeyboardInterrupt:
            print(f"\n⚠ Training manually stopped")
            print(f"   Progress saved. Run this cell again to resume.")
            return False

    print(f"\n✗ Failed to complete fold {fold} after {max_attempts} attempts")
    return False

def check_training_status(dataset_id):
    results_path = Path(os.environ['nnUNet_results']) / f"Dataset{dataset_id}_ISLES2022" / "nnUNetTrainer__nnUNetPlans__3d_fullres"
    print("\n" + "="*70)
    print("Training Status")
    print("="*70)
    for fold in range(5):
        fold_path = results_path / f"fold_{fold}"
        checkpoint_final = fold_path / "checkpoint_final.pth"
        if checkpoint_final.exists():
            size_mb = checkpoint_final.stat().st_size / (1024**2)
            print(f"  Fold {fold}: ✓ Complete ({size_mb:.1f} MB)")
        elif fold_path.exists():
            checkpoints = list(fold_path.glob("checkpoint_*.pth"))
            if checkpoints:
                latest = max(checkpoints, key=lambda p: p.stat().st_mtime)
                print(f"  Fold {fold}: ⏸ In progress (checkpoint: {latest.name})")
            else:
                print(f"  Fold {fold}: ○ Not started")
        else:
            print(f"  Fold {fold}: ○ Not started")

print("✓ Training helper functions loaded")

print("="*70)
print("Training Fold 0 (Test)")
print("="*70)
print("\nThis trains ONLY fold 0 to verify everything works.")
print("\n⚠ IMPORTANT: If Colab disconnects, just re-run this cell.")
print("   Training will automatically resume from the last checkpoint.\n")

input("Press Enter to start training fold 0...")

success = train_fold_with_resume(dataset_id=dataset_id, fold=0)

if success:
    print("\n" + "="*70)
    print("✓ FOLD 0 TRAINING COMPLETE!")
    print("="*70)
    print("\nNext steps:")
    print("  1. Check validation metrics")
    print("  2. If results look good, train remaining folds (1-4)")
    print("  3. Or proceed to evaluation")
else:
    print("\n" + "="*70)
    print("⚠ TRAINING INTERRUPTED")
    print("="*70)
    print("\nTo resume: Just re-run this cell")

check_training_status(dataset_id)

print("="*70)
print("Validating Fold 0")
print("="*70)

!nnUNetv2_train {dataset_id} 3d_fullres 0 --val --npz

print("\n✓ Validation complete! Check output above for Dice scores.")